version: '3'
services:
  build:
    image: build
    volumes:
      - /tmp/outside:/tmp/inside

    command: cp foo/dockertest.txt /tmp/inside/dockertest.txt
    build:
      context: .
      dockerfile: dockerfiles/build/Dockerfile
volumes:
  data:
